# Homework 02

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/Users/hupeipei/Documents/GitHub/QMSS-GR5072-Spring2026-HWs/homework-2-main/Data/Seasons_Stats_NBA.csv')
display(df.head())

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,0.368,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,0.435,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,0.394,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,0.312,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,0.308,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0

## 1.Which NBA player scored the most points in a single season? What seasons/year was this?

In [8]:
top_score = df[df['PTS'] == df['PTS'].max()]

display(top_score[['Player', 'Year', 'PTS']].head())
display(top_score[['Player', 'Year', 'PTS']].tail())

                 Player    Year     PTS
1706  Wilt Chamberlain*  1962.0  4029.0

                 Player    Year     PTS
1706  Wilt Chamberlain*  1962.0  4029.0