# Homework 02

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/Users/hupeipei/Documents/GitHub/QMSS-GR5072-Spring2026-HWs/homework-2-main/Data/Seasons_Stats_NBA.csv')
display(df.head())

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,0.368,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,0.435,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,0.394,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,0.312,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,0.308,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0

## 1.Which NBA player scored the most points in a single season? What seasons/year was this?

In [13]:
top_score = df[df['PTS'] == df['PTS'].max()]

display(top_score[['Player', 'Year', 'PTS']])

                 Player    Year     PTS
1706  Wilt Chamberlain*  1962.0  4029.0

## 2.Which NBA player scored the most points in 1991?

In [14]:
df_1991 = df[df['Year'] == 1991]

top_scorer_1991 = df_1991[df_1991['PTS'] == df_1991['PTS'].max()]

display(top_scorer_1991[['Player','Year','PTS']])

                Player    Year     PTS
10212  Michael Jordan*  1991.0  2580.0

## 3.Which player had the best free throw percentage ("FT%") from the year 2000 to the most recent year in the data? If there are multiple players who have tied for the best percentage, then sort on the column with player names and submit your answer as a pd.DataFrame object.

In [28]:
df_Q3 = df[df['Year']>= 2000]

max_FT = df_Q3['FT%'].max()
result_Q3 = df_Q3[df_Q3['FT%'] == max_FT].sort_values(by='Player')

display(result_Q3.head())
display(result_Q3.tail())

display(result_Q3[['Player', 'Year', 'FT%']].head())
display(result_Q3[['Player', 'Year', 'FT%']].tail())

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
17990,2006.0,Aaron Miles,PG,22.0,GSW,19.0,0.0,118.0,6.0,0.405,...,1.0,0.0,14.0,14.0,24.0,4.0,1.0,11.0,13.0,16.0
16181,2003.0,Adam Harrington,SG,22.0,DAL,13.0,0.0,37.0,1.4,0.308,...,1.0,0.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,11.0
22787,2014.0,Adonis Thomas,SF,20.0,TOT,6.0,1.0,37.0,7.3,0.485,...,1.0,0.0,3.0,3.0,3.0,0.0,0.0,1.0,6.0,14.0
22788,2014.0,Adonis Thomas,SF,20.0,ORL,4.0,0.0,24.0,5.8,0.371,...,1.0,0.0,3.0,3.0,2.0,0.0,0.0,0.0,2.0,7.0
18961,2008.0,Adrian Griffin,SF,33.0,SEA,13.0,0.0,85.0,9.3,0.415,...,1.0,9.0,13.0,22.0,5.0,5.0,1.0,5.0,8.0,14.0

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
16906,2004.0,Wesley Person,SG,32.0,ATL,9.0,0.0,132.0,10.6,0.480,...,1.0,2.0,23.0,25.0,5.0,3.0,1.0,4.0,5.0,40.0
18271,2007.0,Will Blalock,PG,23.0,DET,14.0,0.0,166.0,4.5,0.383,...,1.0,6.0,9.0,15.0,17.0,5.0,0.0,12.0,9.0,25.0
17572,2005.0,Yuta Tabuse,PG,24.0,PHO,4.0,0.0,17.0,15.6,0.451,...,1.0,2.0,2.0,4.0,3.0,0.0,0.0,1.0,1.0,7.0
17167,2005.0,Zarko Cabarkapa,PF,23.0,PHO,3.0,0.0,11.0,32.4,0.605,...,1.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,9.0
16176,2003.0,Zendon Hamilton,C,27.0,TOR,3.0,0.0,12.0,17.7,0.510,...,1.0,1.0,3.0,4.0,0.0,1.0,0.0,1.0,2.0,6.0

                Player    Year  FT%
17990      Aaron Miles  2006.0  1.0
16181  Adam Harrington  2003.0  1.0
22787    Adonis Thomas  2014.0  1.0
22788    Adonis Thomas  2014.0  1.0
18961   Adrian Griffin  2008.0  1.0

                Player    Year  FT%
16906    Wesley Person  2004.0  1.0
18271     Will Blalock  2007.0  1.0
17572      Yuta Tabuse  2005.0  1.0
17167  Zarko Cabarkapa  2005.0  1.0
16176  Zendon Hamilton  2003.0  1.0

## 4.Among those with at least 50 attempts ('FTA'), which player had the best free throw percentage ("FT%") from the year 2000 to the most recent year in the data?

In [33]:
df_Q4 = df[(df['Year'] >= 2000) & (df['FTA'] >= 50)]

max_FT_Q4 = df_Q4['FT%'].max()
result_Q4 = df_Q4[df_Q4['FT%'] == max_FT_Q4].sort_values(by='Player')

display(result_Q4[['Player', 'Year', 'FTA', 'FT%']])

                Player    Year   FTA    FT%
15565  Terrell Brandon  2002.0  84.0  0.988

## 5.Rename the variable "Pos" to "Position".

In [35]:
df.rename(columns={'Pos': 'Position'}, inplace=True)

df.head()

,Year,Player,Position,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,0.368,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,0.435,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,0.394,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,0.312,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,0.308,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0

## 6.Use this variable to create two variables that are called "first_position" and "second_position". Hint: If a player plays two positions, then the "-" is used as a delimiter between their first and second positions. In these cases, you will have to split the position variable into two.

In [36]:
df[['first_position', 'second_position']] = df['Position'].str.split('-', expand=True)

display(df[['Player', 'Position', 'first_position', 'second_position']].head())
display(df[['Player', 'Position', 'first_position', 'second_position']].tail())

            Player Position first_position second_position
0  Curly Armstrong      G-F              G               F
1     Cliff Barker       SG             SG            None
2    Leo Barnhorst       SF             SF            None
3       Ed Bartels        F              F            None
4       Ed Bartels        F              F            None

                  Player Position first_position second_position
24686        Cody Zeller       PF             PF            None
24687       Tyler Zeller        C              C            None
24688  Stephen Zimmerman        C              C            None
24689        Paul Zipser       SF             SF            None
24690        Ivica Zubac        C              C            None

## 7.Combine these two variables back into a single variable called "position_united". Make sure to separate the two positions by "-", as the original data field did. If there is no second position, then there will only be a single position. Again, this is similar to how the original variable was coded. Present a frequency table of "position_united".

In [37]:
def combine_positions(row):
    if row['second_position'] is None or pd.isna(row['second_position']):
        return row['first_position']
    else:
        return f"{row['first_position']}-{row['second_position']}"

In [39]:
df['position_united'] = df.apply(combine_positions, axis=1)

result_Q7 = df['position_united'].value_counts().reset_index()
result_Q7.columns = ['position_united', 'count']

display(result_Q7)

   position_united  count
0               PF   4966
1               SG   4811
2                C   4759
3               SF   4699
4               PG   4648
5                G    139
6                F    123
7              F-C     81
8              G-F     79
9              F-G     60
10             C-F     35
11            C-PF     33
12           SF-SG     30
13           PG-SG     28
14           SG-PG     27
15            PF-C     27
16           SG-SF     26
17           PF-SF     25
18           SF-PF     21
19           SG-PF      3
20            C-SF      2
21           SF-PG      1
22           PG-SF      1