# homework 3 - Functions I

In [1]:
import pandas as pd
import numpy as np

In [6]:
path = r"/Users/hupeipei/Documents/GitHub/QMSS-GR5072-Spring2026-HWs/homework-3-main/Data"
data = pd.read_csv(path + r"/nycflights.csv")
data

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336772,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00
336772,336773,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00
336773,336774,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00
336774,336775,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00
336775,336776,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00

## 1.Write a function that takes a single numerical variable and returns three values, the minimum number, the median, and the maximum number of the vector. Test your function using the month column of the flights data set.

In [11]:
def get_summary_stats(var):
    min_val = var.min()
    med_val = var.median()
    max_val = var.max()
    return min_val, med_val, max_val

get_summary_stats(data["month"])

(1, 7.0, 12)

## 2.Explain your reasoning for choosing your function's name in the previous question.

I chose the name get_summary_stats because it is simple and descriptive. Uses a verb (get) to show the action. The function returns summary statistics for one numerical variable, specifically the minimum, median, and maximum. This name makes the purpose of the function easy to understand when reading the code.

## 3.Write a function that categorizes a numerical variable in the flights data into four categories.
The function should have two arguments. The first should represent the data object and the second should represent a column name in the data object.

The function should return one new column which categorizes the dep_time column into four categories in the following manner. For any particular variable in the flights data that represents military time (i.e., 0 to 2400 where 1200 represents 12 in the afternoon and 2400 represents midnight), the function should classify values into four categories:

"Morning" for values from 5 am to 11:59 am

"Afternoon" for values from 12 pm to 4:59 pm

"Evening" for values from 5 pm to 8:59 pm

"Night" for values from 9 pm to 4:59 am

Test your function using the dep_time column of the flights dataset. Print a frequency table of the output.

In [24]:
def categorize_flight_time(df, col_name):
    
    bins = [0, 499, 1159, 1659, 2059, 2400]
    labels = ["Night", "Morning", "Afternoon", "Evening", "Night"]
    
    df['time_category'] = pd.cut(df[col_name], bins=bins, labels=labels, include_lowest=True, ordered=False)
    
    return df

In [27]:
categorize_flight_time(data, "dep_time")
data["time_category"].value_counts()

time_category
Morning      129539
Afternoon     98617
Evening       79793
Night         20572
Name: count, dtype: int64

## 4.Explain your reasoning for choosing your function's name in the previous question.

I chose the name categorize_flight_time because it follows the naming guidelines: it is short but descriptive, uses a verb (categorize) to show the action, and uses snake_case with underscores for readability. The name also clearly indicates what the function does (categorizes flight time into time-of-day groups) without using vague terms like func or function.

## 5.Write a function that calculates the median of all numeric variables in the flights dataset.
Hint: There are several ways to subset a DF to numeric values only, you will need to search online (using google, stackexchange or some generative AI like chat GPT) to find a suitable way to do so. Alternatively, you could try to do this manually with a for loop, which was reviewed in datacamp, although as a class we are not learning for loops together until next week.

In [28]:
def get_all_numeric_medians(df):
    numeric_df = df.select_dtypes(include = "number")
    medians = numeric_df.median()
    return medians

get_all_numeric_medians(data)

Unnamed: 0        168388.5
year                2013.0
month                  7.0
day                   16.0
dep_time            1401.0
sched_dep_time      1359.0
dep_delay             -2.0
arr_time            1535.0
sched_arr_time      1556.0
arr_delay             -5.0
flight              1496.0
air_time             129.0
distance             872.0
hour                  13.0
minute                29.0
dtype: float64

## 6.Explain your reasoning for choosing your function's name in the previous question.

I named the function get_all_numeric_medians because it is highly descriptive. It starts with a verb and clearly specifies that the function programmatically filters for all numeric columns and calculates their medians, making the code's purpose immediately obvious to any user.

## 7.Modify the function t_test() we wrote in class together this week so that this function can handle violations to the homogeneity of variance (HOV) assumption. 

This assumption is described below in case you are not familiar with it. Please read the class activity carefully - as all of those details are relevant.

In [57]:
# import libraries we need
import scipy.stats as stats

# Create t-test function
def t_test(num_var, bin_var):  
    
    # Calculate the mean difference between the two groups
    group1 = num_var[bin_var == 0]
    group2 = num_var[bin_var == 1]
    mean_diff = group2.mean() - group1.mean()
    
    # Calculate the sample sizes and sample variances of the two groups
    n1 = group1.shape[0]
    n2 = group2.shape[0]
    s2_1 = group1.var()
    s2_2 = group2.var()

    # Compare sample variances
    variance_ratio = s2_1 / s2_2

    #To assess whether the HOV assumption is violated，and to compute Welch's t-test
    if 0.25 > variance_ratio or variance_ratio > 4.0:

        # Calculate the degrees of freedom (DF)
        DF = ((s2_1/n1 + s2_2/n2)**2) / ((1/(n1**(-1)))*((s2_1/n1)**2) + (1/(n2**(-1)))*((s2_2/n2)**2))

        # Calculate the t-statistic
        t_statistic = mean_diff/np.sqrt((s2_1/n1)+(s2_2/n2))

        # Calculate the p-value
        p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), DF))

        method = "Welch's t-test"
        print("The homogeneity of variance assumption was violated, so Welch's t-test was conducted")

    else:
        # Calculate the degrees of freedom (DF)
        DF = n1 + n2 - 2
        
        # Calculate the pooled standard deviation (sp)
        sp = np.sqrt(((n1 - 1) * s2_1 + (n2 - 1) * s2_2) / DF)
        
        # Calculate the standard error of the mean difference
        SE_mean_diff = sp * np.sqrt(1/n1 + 1/n2)
        
        # Calculate the t-statistic
        t_statistic = mean_diff / SE_mean_diff
        
        # Calculate the p-value
        p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), DF))

        method = "Independent samples t-test"
        print("The homogeneity of variance assumption was not violated, so Independent samples t-test was conducted")
    
    # Put the results into a DataFrame
    results = pd.DataFrame({
        "Continuous Variable": [num_var.name],
        "Binary Variable": [bin_var.name],
        "Total Sample Size": [n1 + n2],
        "Mean Difference": [round(mean_diff, 2)], 
        "SE of Mean Difference": [round(SE_mean_diff, 2)],
        "DF": [DF],
        "t-statistic": [round(t_statistic, 3)],
        "P-value": [("%.3f" % p_value).lstrip('0')],
        "Test": method
    })
    
    return results

## 8.Import the GED data set we used for the class activity. Call the t_test() function and test it out on the GED data set we used in class. Let the numeric variable be 'income_log' and let the binary variable be 'ged'.

In [58]:
path = r"/Users/hupeipei/Documents/GitHub/QMSS-GR5072-Spring2026-HWs/homework-3-main/Data"
data02 = pd.read_csv(path + r"/ged_data.csv")
data02

,Unnamed: 0,STU_ID,SCH_ID,F3ERN2011,F3C02,F3EVRGED,F3EVERDO,BYMOTHED,BYS14,BYRACE,...,high_school_grad,ged,BYRACE2,Other,Asian,Black,Hispanic,White,post_sec_edu,income_log
0,2,101104,1011,37000,50,0,0,2,2,7,...,1,0,7,0,0,0,0,1,4,10.518673
1,5,101107,1011,35000,40,0,0,2,1,4,...,1,0,4,0,0,0,1,0,0,10.463103
2,7,101109,1011,68000,40,0,0,2,1,7,...,1,0,7,0,0,0,0,1,4,11.127263
3,10,101112,1011,18000,1,0,0,6,1,3,...,1,0,3,0,0,1,0,0,0,9.798127
4,18,101120,1011,1000,40,1,1,2,1,7,...,0,1,7,0,0,0,0,1,0,6.907755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5971,16179,461202,4612,20000,38,0,1,1,2,5,...,0,0,4,0,0,0,1,0,0,9.903488
5972,16181,461205,4612,100,6,0,1,2,2,5,...,0,0,4,0,0,0,1,0,0,4.605170
5973,16182,461207,4612,29000,40,0,0,3,2,5,...,1,0,4,0,0,0,1,0,2,10.275051
5974,16185,461214,4612,15000,44,0,1,2,1,5,...,0,0,4,0,0,0,1,0,0,9.615805
5975,16193,461231,4612,7000,30,0,1,2,2,4,...,0,0,4,0,0,0,1,0,0,8.853665

In [59]:
results_ged = t_test(data02["income_log"], data02["ged"])
results_ged

The homogeneity of variance assumption was not violated, so Independent samples t-test was conducted

,Continuous Variable,Binary Variable,Total Sample Size,Mean Difference,SE of Mean Difference,DF,t-statistic,P-value,Test
0,income_log,ged,5976,-0.48,0.06,5974,-7.458,.000,Independent samples t-test